// USER
export const GET_USER_START   = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL    = "GET_USER_FAIL";

export const GET_WISHLIST_START   = "GET_WISHLIST_START";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL    = "GET_WISHLIST_FAIL";

// AUTH
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// ADDRESSES
export const GET_ADDRESS_START   = "GET_ADDRESS_START"
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FAIL    = "GET_ADDRESS_FAIL"

//OUTLET
export const GET_OUTLET_START   = "GET_OUTLET_START"
export const GET_OUTLET_SUCCESS = "GET_OUTLET_SUCCESS"
export const GET_OUTLET_FAIL    = "GET_OUTLET_FAIL"

//BRAND
export const GET_BRAND_START   = "GET_BRAND_START"
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS"
export const GET_BRAND_FAIL    = "GET_BRAND_FAIL"

//CATEGORIES
export const GET_CATEGORIES_START   = "GET_CATEGORIES_START"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAIL    = "GET_CATEGORIES_FAIL"

//SUB-CATEGORIES
export const GET_SUBCATEGORIES_START   = "GET_SUBCATEGORIES_START"
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS"
export const GET_SUBCATEGORIES_FAIL    = "GET_SUBCATEGORIES_FAIL"

//ITEM-SUB-CATEGORIES
export const GET_ITEMSUBCATEGORIES_START   = "GET_ITEMSUBCATEGORIES_START"
export const GET_ITEMSUBCATEGORIES_SUCCESS = "GET_ITEMSUBCATEGORIES_SUCCESS"
export const GET_ITEMSUBCATEGORIES_FAIL    = "GET_ITEMSUBCATEGORIES_FAIL"

//ALL-CATEGORIES
export const GET_ALLCATEGORIES_START   = "GET_ALLCATEGORIES_START"
export const GET_ALLCATEGORIES_SUCCESS = "GET_ALLCATEGORIES_SUCCESS"
export const GET_ALLCATEGORIES_FAIL    = "GET_ALLCATEGORIES_FAIL"

//PRODUCT 
export const GET_ALLPRODUCTS_START   = "GET_ALLPRODUCTS_START"
export const GET_ALLPRODUCTS_SUCCESS = "GET_ALLPRODUCTS_SUCCESS"
export const GET_ALLPRODUCTS_FAIL    = "GET_ALLPRODUCTS_FAIL"

export const GET_PRODUCT_SLUG_START   = "GET_PRODUCT_SLUG_START"
export const GET_PRODUCT_SLUG_SUCCESS = "GET_PRODUCT_SLUG_SUCCESS"
export const GET_PRODUCT_SLUG_FAIL    = "GET_PRODUCT_SLUG_FAIL"

export const DELETE_PRODUCTS_START   = "DELETE_PRODUCTS_START"
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS"
export const DELETE_PRODUCTS_FAIL    = "DELETE_PRODUCTS_FAIL"

export const ALIVE_ARCHIVE_START   = "ALIVE_ARCHIVE_START"
export const ALIVE_ARCHIVE_SUCCESS = "ALIVE_ARCHIVE_SUCCESS"
export const ALIVE_ARCHIVE_FAIL    = "ALIVE_ARCHIVE_FAIL"

export const LOVE_PRODUCT_START   = "LOVE_PRODUCT_START"
export const LOVE_PRODUCT_SUCCESS = "LOVE_PRODUCT_SUCCESS"
export const LOVE_PRODUCT_FAIL    = "LOVE_PRODUCT_FAIL"

export const UNLOVE_PRODUCT_START   = "UNLOVE_PRODUCT_START"
export const UNLOVE_PRODUCT_SUCCESS = "UNLOVE_PRODUCT_SUCCESS"
export const UNLOVE_PRODUCT_FAIL    = "UNLOVE_PRODUCT_FAIL"

export const SEARCH_NAME_START   = "SEARCH_NAME_START"
export const SEARCH_NAME_SUCCESS = "SEARCH_NAME_SUCCESS"
export const SEARCH_NAME_FAIL    = " SEARCH_NAME_FAIL"

//DISCOUNT
export const GET_ALLDISCOUNT_START   = "GET_ALLDISCOUNT_START"
export const GET_ALLDISCOUNT_SUCCESS = "GET_ALLDISCOUNT_SUCCESS"
export const GET_ALLDISCOUNT_FAIL    = "GET_ALLDISCOUNT_FAIL"

export const NON_ACTIVE_DISCOUNT_START   = "NON_ACTIVE_DISCOUNT_START"
export const NON_ACTIVE_DISCOUNT_SUCCESS = "NON_ACTIVE_DISCOUNT_SUCCESS"
export const NON_ACTIVE_DISCOUNT_FAIL    = "NON_ACTIVE_DISCOUNT_FAIL"

//SHIPPING
export const SEARCH_CITY_DISTRICT_START   = "SEARCH_CITY_DISTRICT_START"
export const SEARCH_CITY_DISTRICT_SUCCESS = "SEARCH_CITY_DISTRICT_SUCCESS"
export const SEARCH_CITY_DISTRICT_FAIL    = "SEARCH_CITY_DISTRICT_FAIL"

export const GET_SHIPPING_COST_START   = "GET_SHIPPING_COST_START"
export const GET_SHIPPING_COST_SUCCESS = "GET_SHIPPING_COST_SUCCESS"
export const GET_SHIPPING_COST_FAIL    = "GET_SHIPPING_COST_FAIL"

//COMENTS
export const GET_ALLCOMMENTS_START   = "GET_ALLCOMMENTS_START"
export const GET_ALLCOMMENTS_SUCCESS = "GET_ALLCOMMENTS_SUCCESS"
export const GET_ALLCOMMENTS_FAIL    = "GET_ALLCOMMENTS_FAIL"

//PROMOS
export const SEARCH_PROMO_NAME_START   = "SEARCH_PROMO_NAME_START"
export const SEARCH_PROMO_NAME_SUCCESS = "SEARCH_PROMO_NAME_SUCCESS"
export const SEARCH_PROMO_NAME_FAIL    = " SEARCH_PROMO_NAME_FAIL"

export const GET_PROMO_START   = "GET_PROMO_START"
export const GET_PROMO_SUCCESS = "GET_PROMO_SUCCESS"
export const GET_PROMO_FAIL    = "GET_PROMO_FAIL"

export const DELETE_PROMO_START   = "DELETE_PROMO_START"
export const DELETE_PROMO_SUCCESS = "DELETE_PROMO_SUCCESS"
export const DELETE_PROMO_FAIL    = "DELETE_PROMO_FAIL"

//LAYOUT
export const GET_ADMIN_COLLAPSED = "GET_ADMIN_COLLAPSED"
export const GET_ADMIN_IS_MOBILE = "GET_ADMIN_IS_MOBILE"
