// USER
export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

// AUTH
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// ADDRESSES
export const GET_ADDRESS_START = "GET_ADDRESS_START"
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL"

//OUTLET
export const GET_OUTLET_START = "GET_OUTLET_START"
export const GET_OUTLET_SUCCESS = "GET_OUTLET_SUCCESS"
export const GET_OUTLET_FAIL = "GET_OUTLET_FAIL"

//BRAND
export const GET_BRAND_START = "GET_BRAND_START"
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS"
export const GET_BRAND_FAIL = "GET_BRAND_FAIL"

//CATEGORIES
export const GET_CATEGORIES_START = "GET_CATEGORIES_START"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL"

//SUB-CATEGORIES
export const GET_SUBCATEGORIES_START = "GET_SUBCATEGORIES_START"
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS"
export const GET_SUBCATEGORIES_FAIL = "GET_SUBCATEGORIES_FAIL"

//ITEM-SUB-CATEGORIES
export const GET_ITEMSUBCATEGORIES_START = "GET_ITEMSUBCATEGORIES_START"
export const GET_ITEMSUBCATEGORIES_SUCCESS = "GET_ITEMSUBCATEGORIES_SUCCESS"
export const GET_ITEMSUBCATEGORIES_FAIL = "GET_ITEMSUBCATEGORIES_FAIL"

//ALL-CATEGORIES
export const GET_ALLCATEGORIES_START = "GET_ALLCATEGORIES_START"
export const GET_ALLCATEGORIES_SUCCESS = "GET_ALLCATEGORIES_SUCCESS"
export const GET_ALLCATEGORIES_FAIL = "GET_ALLCATEGORIES_FAIL"

//PRODUCT 
export const GET_ALLPRODUCTS_START = "GET_ALLPRODUCTS_START"
export const GET_ALLPRODUCTS_SUCCESS = "GET_ALLPRODUCTS_SUCCESS"
export const GET_ALLPRODUCTS_FAIL = "GET_ALLPRODUCTS_FAIL"

export const ALIVE_ARCHIVE_START = "ALIVE_ARCHIVE_START"
export const ALIVE_ARCHIVE_SUCCESS = "ALIVE_ARCHIVE_SUCCESS"
export const ALIVE_ARCHIVE_FAIL = "ALIVE_ARCHIVE_FAIL"

//LAYOUT
export const GET_ADMIN_COLLAPSED = "GET_ADMIN_COLLAPSED"
export const GET_ADMIN_IS_MOBILE = "GET_ADMIN_IS_MOBILE"
