// USER
export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

// AUTH
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// ADDRESSES
export const GET_ADDRESS_START = "GET_ADDRESS_START"
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL"
